Develop
cobuildlab/pex-cmd pull request #5
Opened 2019-04-18 23:36 UTC by arthurnavah

2019-04-18 23:39 UTC, alacret requested changes

2019-04-18 23:39 UTC, alacret commented on merchant-files/download_all.go
> +	err = os.Remove("./upload.lock")
aqui es download.lock

2019-04-18 23:39 UTC, alacret commented on merchant-files/upload_all.go
> +		if exist {
tambien añade aqui un print con el time diciendo que no se pudo arrancar el proceso por que se encontro el archivo

2019-04-18 23:39 UTC, alacret commented on merchant-files/download_all.go
> +		if exist {
tambien añade aqui un print con el time diciendo que no se pudo arrancar el proceso por que se encontro el archivo

2019-04-19 02:22 UTC, arthurnavah commented on merchant-files/upload_all.go
> +		if exist {
Listo

2019-04-19 02:22 UTC, arthurnavah commented on merchant-files/download_all.go
> +		if exist {
Listo

2019-04-19 02:22 UTC, arthurnavah commented on merchant-files/download_all.go
> +	err = os.Remove("./upload.lock")
Listo

2019-04-19 13:05 UTC, alacret approved these changes

2019-04-19 13:05 UTC, merged